### ISSUE TITLE
Incompatible thor dependency with foreman

### ISSUE THREAD

**Issue by chrismo** [braintree/runbook#1]
https://github.com/ddollar/foreman/blob/master/foreman.gemspec#L20

Foreman is strictly tied to ~> 0.19.x

`gem.add_dependency 'thor', '~> 0.19.1'`

Runbook to 0.20.x. Any chance y'all don't need 0.20.x but could live with an older version of it?

(If I allow it, Bundler can _downgrade_ foreman to an older version that is more permissive of thor, but it's back to a time around 0.13 of thor, not sure how old all that is).

**Comment by pblesi** [comment]
Unfortunately, Runbook isn't compatible with Thor < 0.20.0. I suggest following up on this issue: https://github.com/ddollar/foreman/issues/735
