### ISSUE TITLE
Best practices

### ISSUE THREAD

**Issue by pitosalas** [braintree/runbook#27]
I'm looking for more examples than are in github so I can learn best practices with runbook. For example, I assume that there's one runbook for each of my goals/tasks/objectives whatever you want to call them?  So I might have `runbook exec initialize_servers`, `runbook exec restart_servers` etc.? Is there a resource where I can read about that? (Assume that I've read the doc page fully even though I've actually jumped around and might have missed it right there :)

**Comment by pblesi** [comment]
Here is a runbook I've written to update SSL certificates: http://patrick.ble.si/ssl-cert-rotation-with-runbook

Generally speaking, it makes sense as you said to have a single runbook per objective. I do not have a good resource for overall runbook best practices, but will look to create something in the future. Happy to answer any specific questions you have around good practices.

**Comment by pitosalas** [comment]
Thanks!

Pito Salas
Brandeis Computer Science
Volen 134
