### ISSUE TITLE
How does "previous position detected" work?

### ISSUE THREAD

**Issue by pitosalas** [braintree/runbook#29]
I keep getting this message (while I am just experimenting):

```
Previous position detected: 1.4
Do you want to resume at this position? (Y/n) 
```
1. How is the "previous position detected" work, where is it stored?
1. If I don't want to be asked, i.e. always begin at first position, how do I do that?

Thanks,

**Comment by pblesi** [comment]
Here is the logic for prompting to start from your previous position: 
https://github.com/braintree/runbook/blob/9d468ff2976abe4bd4709256b311b3d239d93f9e/lib/runbook/runner.rb#L29-L34

The state is stored here: https://github.com/braintree/runbook/blob/9d468ff2976abe4bd4709256b311b3d239d93f9e/lib/runbook/util/stored_pose.rb#L25

You can skip this by passing `-s 1` at the command line (this will instruct runbook to start at step 1 and the previous position check only runs if you do not specify to start at a specific position).

**Comment by pitosalas** [comment]
Awesome, thanks!
