### ISSUE TITLE
Dealing with errors

### ISSUE THREAD

**Issue by pitosalas** [braintree/runbook#30]
What if the `command` fails?

```
Exception while executing as rails@174.138.58.21: git exit status: 128 (SSHKit::Runner::ExecuteError)
git stdout: Nothing written
git stderr: fatal: destination path 'soa_demo' already exists and is not an empty directory. 
```

What's the recommended way to handle this situation?

**Comment by pblesi** [comment]
Typically if an error occurs while executing a command it is an unexpected state and it is safest to exit the runbook and have a manual operator assess the situation. If it is expected that a command can fail and it should not be a critical error that halts the runbook, you can append `|| true` to the command and this will prevent the command from returning a fatal error (non-zero status code).

In some cases you may want to use the [assert statement](https://github.com/braintree/runbook#assert`) to test for a specific state multiple times if you expect that will not return a failure after some period of time or number of tries.

**Comment by pitosalas** [comment]
Thanks
