### ISSUE TITLE
tmux_command doesn't seem to respect server

### ISSUE THREAD

**Issue by pitosalas** [braintree/runbook#33]
My tmux_command is being executed locally. I want it to first ssh to the server and then execute. How come is that not happening? It seems to defeat the purpose. In other words, it seems like the key use of tmux in this scenario would be to have a pane showing what's happening on server A and another one for server B. Especially if the last step on Server A is a long running process (e.g. httpd) that is handling requests. Or am I thinking of this wrong?

**Comment by pblesi** [comment]
[Tmux](https://github.com/tmux/tmux) itself is not inherently multi-server, as such runbook is a wrapper on top of tmux and each tmux pane is a shell that is executed locally. There is a possibility to create something like a remote tmux  page that would handle the lifecycle of sshing to a remote host for tmux command  execution. Nothing like this exists  currently.

One option for this is to use the `command` argument that can be passed to tmux layout panes: https://github.com/braintree/runbook#tmux-layouts

This command could be responsible for  ssh'ing to the remote host. You would likely want to make sure this command is reliable in this case, by having the ssh command always  accept unknown host keys, etc.

Does this answer your question?

**Comment by pitosalas** [comment]
Hi Patrick

Yes absolutely!

Pito Salas
Brandeis Computer Science
Volen 134
