### ISSUE TITLE
Ability to set `report_on_exception = false`?

### ISSUE THREAD

**Issue by iphoting** [braintree/runbook#36]
Sometimes, some commands executed on SSH will return an exit status > 0 or output into StdError. In such cases, runbook will throw the SSHKit exception and exits, disallowing the remaining steps to be run.

Is there a way to suppress these known error conditions and continue the runbook execution?
Or is there a way to set `report_on_exception = false` into the underlying SSHKit config object.

**Comment by pblesi** [comment]
The typical pattern for doing this is to append and `|| true` to the end of your shell command. This will prevent the command from returning a non-zero status code. I'm not familiar with `report_on_exception`, but would be curious to look more into this in the event it provides better functionality than `|| true`

**Comment by iphoting** [comment]
Ah, the `|| true` pattern is perfect for my situation. Looks like dealing with `report_on_exception` is not really necessary, please feel free to close this. 😀
