### ISSUE TITLE
can't override system ssh user setting at all 

### ISSUE THREAD

**Issue by blysik** [braintree/runbook#4]
Running on macOS 10.14.5.
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
runbook (0.13.0)

No matter where I set the "user" command, it always falls back to my personal username.

I've tried in the section, step, and using the ssh_command overrides.  Still nothing.

**Comment by blysik** [comment]
Please let me know what troubleshooting/debugging info you need.  Thanks!

**Comment by pblesi** [comment]
The `user` command is used to specify the user that you will sudo execute the command as once you connect using ssh. I'm guessing you are looking to connect to your server using a specified user and not your personal username. In this case you can either update your server string to be like the following:

```
server "root@app01.prod"
```

Or you could use your `~/.ssh/config` file to designate the user when connecting to a specific host. Something like:

```
Host dev
    HostName dev.example.com
    User john
    Port 2322
```

Then you could specify your server as `dev` and it will know to connect to `john@dev.example.com:2322` by using your `~/.ssh/config` file. 

Here's more info on configuring `~/.ssh/config`: https://linuxize.com/post/using-the-ssh-config-file/

If this doesn't resolve your issue, feel free to reopen

**Comment by blysik** [comment]
That was it, thanks.
