### ISSUE TITLE
[question] how to constrain a set of steps to 1 server, before going to the next

### ISSUE THREAD

**Issue by blysik** [braintree/runbook#5]
Hi,

I'm trying to figure out the proper way to do something like this:

For a list of servers, do ALL the following steps before going to the next server:

* stop a service
  * verify stopped
* start a service
  * verify started

If I use a 2 steps, in a section, it will go through the first step for all servers first, then the second step for all servers.  But that's not the behavior I'm looking for.

What do you consider the best design pattern for this?  Thanks!

**Comment by pblesi** [comment]
The typical approach to this is to use a standard ruby loop to generate the steps. Something like...

```
["app01.prod", "app02.prod", "app03.prod"].each_slice(2) do |server_list|
  section "Do for servers #{server_list}" do
    servers server_list

    step "Stop service" { command "echo hi" }
    step "Start service" { command "echo world" }
  end
end
```
