### ISSUE TITLE
Error: layout statement called outside a tmux pan

### ISSUE THREAD

**Issue by wiiikiii** [braintree/runbook#6]
running the sample script ``layout_runbook.rb`` from this repo
I get the error 

    Error: layout statement called outside a tmux pane. Exiting...

I am running MacOs 10.13.6 with tux 2.8

**Comment by pblesi** [comment]
You must be inside a session for Runbook to work with tmux. Here is a helpful guide for tmux: https://thoughtbot.com/blog/a-tmux-crash-course#session-management

You will want to run:

```
tmux new -s session_name
tmux attach -t session_name
```
And then you can execute your runbook at the prompt inside the tmux.
