### ISSUE TITLE
Incompatibilities to tmux version 3.4

### ISSUE THREAD

**Issue by whysthatso** [braintree/runbook#64]
I've just updated from tmux-3.3_a-7-x86_64 to  tmux-3.4-3-x86_64 on archlinux, and that seems to break at least the `pane-swap` integration:

`command swap-pane: too many arguments (need at most 0)`

 and i get two times this error:
 
 `size missing` 

This happens during layout configuration:

```
  layout [[
    {:left => 1, {name: :right, runbook_pane: true} => 2},
    {bottom: 1}
  ]]
```

**Comment by AlexanderPavlenko** [comment]
https://github.com/tmux/tmux/issues/3836#issuecomment-1945034174
https://github.com/tmux/tmux/pull/3840

**Comment by whysthatso** [comment]
yep, installing tmux-git on archlinux fixes my issues
