### ISSUE TITLE
tty-prompt in gemspec seems to be out of date

### ISSUE THREAD

**Issue by obromios** [braintree/runbook#7]
When I ```bundle install``` after putting ```runbook``` in my gemfile, I get the following

 ```
  Bundler could not find compatible versions for gem "tty-prompt":
  In snapshot (Gemfile.lock):
   tty-prompt (= 0.19.0)

  In Gemfile:
    tty-prompt

    runbook was resolved to 0.13.0, which depends on
      tty-prompt (~> 0.16.0)

```
I could revert to ```0.16.0``` of ```tty-prompt``` but that is more than a year older than the latest version.

**Comment by pblesi** [comment]
That makes sense. I'll update Runbook's gemspec to be less restrictive. The update will be released in 0.14.0.

**Comment by obromios** [comment]
Thank you. As a relentless to-do list maker and enthusiastic bash scripter,
runbook combines two of my passions, so am looking forward to trying it out.

**Comment by pblesi** [comment]
Runbook version 0.14.0 has been released. Happy Runbooking!
