### ISSUE TITLE
Rake isn't a runtime dependency

### ISSUE THREAD

**Issue by robmiller** [braintree/runbook#9]
I started a project as per the installation instructions, and got an exception when running `runbook generate runbook`:

```
/Users/rob/.rvm/gems/ruby-2.6.1/gems/airbrussh-1.3.2/lib/airbrussh/rake/context.rb:1:in `require': cannot load such file -- rake (LoadError)
```

Rake is only listed as a development dependency in the gemspec, but is clearly required at run time. I fixed it by adding Rake to my gemfile, but I guess you might want to fix the gemspec.

Best,
Rob

**Comment by pblesi** [comment]
Rake is not a dependency of Runbook, but a dependency of airbrussh. I've submitted an issue with them: https://github.com/mattbrictson/airbrussh/issues/126

**Comment by pblesi** [comment]
This issue has been addressed downstream: https://github.com/mattbrictson/airbrussh/issues/126

If you `bundle update airbrussh`, then you will no longer need to explicitly require rake. 

Cheers
